Feature/use postgre sql
oneleif/olWebsite pull request #70
Opened 2020-02-27 00:55 UTC by 0xLeif

2020-02-27 00:56 UTC, 0xLeif commented
Linux Tests:
```
Test Suite 'ValidatorServiceTests' passed at 2020-02-27 00:56:03.572
	 Executed 5 tests, with 0 failures (0 unexpected) in 0.001 (0.001) seconds
Test Suite 'debug.xctest' passed at 2020-02-27 00:56:03.572
	 Executed 14 tests, with 0 failures (0 unexpected) in 1.996 (1.996) seconds
Test Suite 'All tests' passed at 2020-02-27 00:56:03.572
	 Executed 14 tests, with 0 failures (0 unexpected) in 1.996 (1.996) seconds
```

2020-02-27 00:56 UTC, 0xLeif commented
Ran Tests with: `swift test --enable-test-discovery`

2020-02-27 01:04 UTC, 0xLeif commented
Fixed Tests so one doesn't have to use `swift test --enable-test-discovery`.

One can simply use `swift test`

2020-02-27 01:08 UTC, 0xLeif commented
Seems like tests are failing due to the fact that the CI doesn't have a PostgreSQL server running locally...

2020-02-27 01:09 UTC, 0xLeif commented on Sources/App/configure.swift
> +    let config = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "leif", database: "leif", password: "sudo", transport: .cleartext)
Need to change to use a default one for DEBUG and one for RELEASE

2020-02-27 04:15 UTC, ambid17 approved these changes

2020-02-27 04:20 UTC, ambid17 commented on Sources/App/configure.swift
> +    let config = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "oneleif", database: "website", password: "sudo", transport: .cleartext)
dont need password

2020-02-27 04:20 UTC, ambid17 commented on Sources/App/configure.swift
> -    databases.add(database: sqlite, as: .sqlite)
check out multiline comments

2020-02-27 07:07 UTC, arkus7 commented
I'll review the code in my evening 😛I can manage the circleci to create database while testing 😀

2020-02-27 18:24 UTC, arkus7 requested changes

2020-02-27 18:24 UTC, arkus7 commented on Sources/App/configure.swift
> +    let config = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "oneleif", database: "website", password: "sudo", transport: .cleartext)
I think we should load the credentials from environment variables, so we can quickly change the credentials without having to update the application code.

```swift
let config = PostgreSQLDatabaseConfig(
  hostname: Environment.get("DB_HOST") ?? "localhost", 
  port: Int(Environment.get("DB_PORT") ?? "") ?? 5432, 
  username: Environment.get("DB_USER") ?? "oneleif", 
  database: Environment.get("DB_NAME") ?? "oneleif-\(env.name)", 
  password: Environment.get("DB_PASSWORD") ?? "root", 
  transport: .cleartext
)
```

2020-02-27 19:43 UTC, arkus7 requested changes

2020-02-27 19:43 UTC, arkus7 commented on .circleci/config.yml
> +      - image: circleci/postgres:latest
We need this also for the `test-release` job

2020-02-29 23:02 UTC, arkus7 requested changes

2020-02-29 23:02 UTC, arkus7 commented on Sources/App/configure.swift
> +    let config = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "postgres", database: "website", transport: .cleartext)
Remove this, the config is duplicated now

2020-03-02 18:57 UTC, arkus7 approved these changes

2020-03-02 18:58 UTC, merged